FROM ubuntu:18.04
RUN apt update
RUN apt install openjdk-8-jdk wget -y
RUN wget https://spc-pet.s3.ap-south-1.amazonaws.com/spring-petclinic.jar
EXPOSE 8080
CMD ["java", "-jar", "/spring-petclinic.jar"]
